language: cpp

git:
  depth: 200

matrix:
  include:
    - os: linux
      compiler: gcc
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cmake
      env:
        - COMPILER_CC=gcc-7
        - COMPILER_CXX=g++-7
    - os: osx
      osx_image: xcode8.3
      compiler: clang++
      env:
        - COMPILER_CC=clang
        - COMPILER_CXX=clang++

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_C_COMPILER=$COMPILER_CC -DCMAKE_CXX_COMPILER=$COMPILER_CXX
  - make
